# docker 빌드 후 ecr 업로드 및 kubectl apply

name: deploy tweety with k8s
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET}}
          aws-region: ap-northeast-2

      - name: update cluster information
        run: aws eks update-kubeconfig --name switht-server --region ap-northeast-2

      - name: login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker member image to ecr
        env:
          REGISTRY: 533267389389.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: tweety-member
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest \
          -f ./member/Dockerfile ./member
          docker push $REGISTRY/$REPOSITORY:latest

      - name: eks kubectl apply
        run: |
          kubectl apply -f ./member/k8s/member_depl.yml
          kubectl rollout restart deployment member-deployment -n tweety

      - name: build and push docker lecture image to ecr
        env:
          REGISTRY: 533267389389.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: tweety-lecture
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest \
          -f ./lecture/Dockerfile ./lecture
          docker push $REGISTRY/$REPOSITORY:latest

      - name: eks kubectl apply
        run: |
          kubectl apply -f ./lecture/k8s/lecture_depl.yml
          kubectl rollout restart deployment lecture-deployment -n tweety

      - name: build and push docker payment image to ecr
        env:
          REGISTRY: 533267389389.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: tweety-payment
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest \
          -f ./payment/Dockerfile ./payment
          docker push $REGISTRY/$REPOSITORY:latest

      - name: eks kubectl apply
        run: |
          kubectl apply -f ./payment/k8s/payment_depl.yml
          kubectl rollout restart deployment payment-deployment -n tweety